#!/bin/bash

echo "=== Lyrika Extension Reload Helper ==="
echo "This script will help you reload your extension in Chrome."
echo ""
echo "Steps to follow:"
echo "1. Go to chrome://extensions/ in your Chrome browser"
echo "2. Make sure Developer mode is enabled (toggle in top right)"
echo "3. Find the Lyrika extension and click the refresh icon"
echo "4. If the extension isn't loaded yet, click 'Load unpacked' and select the 'extension' folder"
echo ""
echo "The extension has been updated with these fixes:"
echo "- Bootstrap files are now loaded locally instead of from CDN"
echo "- Added permissions for port 5001 and Last.fm API"
echo "- Updated Content Security Policy to fix script loading issues"
echo ""
echo "After reloading, try using the extension again!"
echo ""
echo "If you still encounter issues, check the Chrome DevTools console for errors."
echo "You can open DevTools for the extension by right-clicking the extension popup and selecting 'Inspect'." 